export const links = [
    'rhythm assemblage: avalon stairs',
    'recent sketches, 2020',
    'a room that i take care of',
    'structure couples',
    'rhythm assemblage: overhead lines',
    'stridulating prototype',
    "don't fog yourself with rosy clouds, or yellow",
    'the wind repeats itself: blue grama',
    'sounding out spaces: garden ecologies',
    'time lenses: palimpsest',
    'invisible lines',
    'music for lamps',
    'aurora urbem',
    'montreal sound map',
];

const portfolioLinks = [
    'rhythm assemblage: avalon stairs',
    'recent sketches, 2020',
    'time is out of joint',
    'artificial ecologies',
    'Whispering Wishes',
    'a room that i take care of',
    'structure couples',
    'rhythm assemblage: overhead lines',
    'stridulating prototype',
    "don't fog yourself with rosy clouds, or yellow",
    'the wind repeats itself: blue grama',
    'MindTravel',
    'Sounding Out Spaces: Garden Ecologies',
    'Time Lenses: Palimpsest',
    'SERRA',
    'dans le bois',
    'Turcot: la route devenue architecture',
    "Einstein's Dreams",
    'Invisible Lines',
    'Music for Lamps',
    'aurora urbem',
    'Montreal Sound Map',
];
